version: 2
updates:
  # Maintain dependencies for GitHub Actions.
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    groups:
      "GitHub Actions (Minor/Patch)":
        update-types:
          - "minor"
          - "patch"

  # Maintain dependencies for Rust/Cargo.
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    groups:
      "Cargo Dependencies (Minor/Patch)":
        update-types:
          - "minor"
          - "patch"

  # Maintain dependencies for Rust/Toolchain.
  - package-ecosystem: "rust-toolchain"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7

  # Maintain dependencies for Docker (Containerfiles).
  - package-ecosystem: "docker"
    directory: "/oci/eidola-server"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7

  - package-ecosystem: "docker"
    directory: "/oci/postgresql"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7

  - package-ecosystem: "docker"
    directory: "/oci/tinfoil-shim-mock"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7

  - package-ecosystem: "docker"
    directory: "/oci/stripe-cli"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
