version: 2
updates:
  # Maintain dependencies for GitHub Actions.
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      "GitHub Actions (Minor/Patch)":
        update-types:
          - "minor"
          - "patch"

  # Maintain dependencies for Rust/Cargo.
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      "Cargo Dependencies (Minor/Patch)":
        update-types:
          - "minor"
          - "patch"

  # Maintain dependencies for Rust/Toolchain.
  - package-ecosystem: "rust-toolchain"
    directory: "/"
    schedule:
      interval: "weekly"

  # Maintain dependencies for Docker (Containerfiles).
  - package-ecosystem: "docker"
    directory: "/oci/eidolons-server"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/oci/postgresql"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/oci/tinfoil-shim-mock"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/oci/stripe-cli"
    schedule:
      interval: "weekly"

  # Maintain dependencies for Swift Package Manager.
  - package-ecosystem: "swift"
    directory: "/core/swift"
    schedule:
      interval: "weekly"
