//! Generates `$OUT_DIR/measurements.gen.rs` with the allowed Tinfoil
//! inference-enclave measurements that the server's outbound verifier accepts.
//!
//! Input: `releases/trust/tinfoil-enclaves.json` at the workspace root —
//! a versioned JSON file maintained by `.github/workflows/update-measurements.yml`
//! when Tinfoil publishes a new enclave build. Putting the data in JSON instead
//! of hand-written Rust matches the pattern `eidola-app-core/build.rs` uses for
//! the client trust root, makes the contents easier to audit in a PR diff, and
//! gives us a `schema_version` gate so a future shape change can't slip through
//! silently.

use std::env;
use std::fmt::Write;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let workspace_root = manifest_dir
        .parent()
        .and_then(Path::parent)
        .expect("workspace root above crates/eidola-server")
        .to_path_buf();

    let json_path = workspace_root.join("releases/trust/tinfoil-enclaves.json");

    println!("cargo:rerun-if-changed={}", json_path.display());
    println!("cargo:rerun-if-changed=build.rs");

    let bytes =
        fs::read(&json_path).unwrap_or_else(|e| panic!("read {}: {e}", json_path.display()));
    let value: serde_json::Value = serde_json::from_slice(&bytes)
        .unwrap_or_else(|e| panic!("parse {}: {e}", json_path.display()));

    let schema_version = value
        .get("schema_version")
        .and_then(|v| v.as_u64())
        .and_then(|n| u32::try_from(n).ok())
        .expect("tinfoil-enclaves.json missing or invalid `schema_version`");
    if schema_version != 1 {
        panic!(
            "tinfoil-enclaves.json schema_version `{schema_version}` is not supported by this build.rs (expected `1`)"
        );
    }

    let source_repo = value
        .get("source_repo")
        .and_then(|v| v.as_str())
        .expect("tinfoil-enclaves.json missing `source_repo`");

    let allowed = value
        .get("allowed")
        .and_then(|v| v.as_array())
        .expect("tinfoil-enclaves.json missing `allowed` array");
    if allowed.is_empty() {
        panic!("tinfoil-enclaves.json `allowed` array must be non-empty");
    }

    let mut out = String::new();
    out.push_str(
        "// @generated by build.rs from releases/trust/tinfoil-enclaves.json — do not edit.\n\n",
    );
    writeln!(out, "// Source repo: {source_repo}").unwrap();
    out.push('\n');
    out.push_str("pub static ALLOWED: std::sync::LazyLock<Vec<tinfoil_verifier::EnclaveMeasurement>> = std::sync::LazyLock::new(|| {\n");
    out.push_str("    vec![\n");

    for entry in allowed {
        let git_tag = get_str(entry, "git_tag");
        let built_at = get_str(entry, "built_at");
        let artifact_digest = get_str(entry, "artifact_digest");
        let rekor_log_index = entry
            .get("rekor_log_index")
            .and_then(|v| v.as_u64())
            .expect("entry missing `rekor_log_index`");

        let snp = get_hex(entry, "snp_measurement", 96);
        let tdx = entry
            .get("tdx_measurement")
            .expect("entry missing `tdx_measurement`");
        let rtmr1 = get_hex(tdx, "rtmr1", 96);
        let rtmr2 = get_hex(tdx, "rtmr2", 96);

        writeln!(
            out,
            "        // {git_tag} — built {built_at}, artifact {artifact_digest}, Rekor log {rekor_log_index}"
        ).unwrap();
        out.push_str("        tinfoil_verifier::EnclaveMeasurement {\n");
        writeln!(out, "            snp_measurement: {snp:?}.into(),").unwrap();
        out.push_str("            tdx_measurement: tinfoil_verifier::TdxMeasurement {\n");
        writeln!(out, "                rtmr1: {rtmr1:?}.into(),").unwrap();
        writeln!(out, "                rtmr2: {rtmr2:?}.into(),").unwrap();
        out.push_str("            },\n");
        out.push_str("        },\n");
    }

    out.push_str("    ]\n");
    out.push_str("});\n");

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    fs::write(out_dir.join("measurements.gen.rs"), out).expect("write measurements.gen.rs");
}

fn get_str<'a>(value: &'a serde_json::Value, key: &str) -> &'a str {
    value
        .get(key)
        .and_then(|v| v.as_str())
        .unwrap_or_else(|| panic!("entry missing string field `{key}`"))
}

fn get_hex(value: &serde_json::Value, key: &str, expected_len: usize) -> String {
    let s = get_str(value, key).to_ascii_lowercase();
    if s.len() != expected_len || !s.chars().all(|c| c.is_ascii_hexdigit()) {
        panic!("`{key}` must be {expected_len} lowercase hex chars, got {s:?}");
    }
    s
}
