//! Embeds the pinned Sigstore trusted root into the server binary.
//!
//! Input: `releases/trust/sigstore-trusted-root.json` at the workspace root
//! — a snapshot of Sigstore's public Fulcio CAs + Rekor keys, the same file
//! the client's updater embeds via `eidola-app-core/build.rs`. The runtime
//! upstream-measurement resolver (`src/upstream_trust`) verifies Tinfoil's
//! release attestations against it.
//!
//! The server no longer embeds a static allowed-measurement set: the allowed
//! upstream measurement is resolved (and Sigstore-verified) at runtime from
//! Tinfoil's latest release. See `src/upstream_trust`.

use std::env;
use std::fmt::Write;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let workspace_root = manifest_dir
        .parent()
        .and_then(Path::parent)
        .expect("workspace root above crates/eidola-server")
        .to_path_buf();

    println!("cargo:rerun-if-changed=build.rs");

    let sigstore_trusted_root_path =
        workspace_root.join("releases/trust/sigstore-trusted-root.json");
    println!(
        "cargo:rerun-if-changed={}",
        sigstore_trusted_root_path.display()
    );
    // Parse-check at build time so a malformed snapshot fails the build, not a
    // request at runtime.
    let sigstore_bytes = fs::read(&sigstore_trusted_root_path)
        .unwrap_or_else(|e| panic!("read {}: {e}", sigstore_trusted_root_path.display()));
    serde_json::from_slice::<serde_json::Value>(&sigstore_bytes)
        .unwrap_or_else(|e| panic!("parse {}: {e}", sigstore_trusted_root_path.display()));

    let mut out = String::new();
    out.push_str("// @generated by build.rs — do not edit.\n");
    writeln!(
        out,
        "pub const SIGSTORE_TRUSTED_ROOT_JSON: &str = include_str!({:?});",
        sigstore_trusted_root_path
    )
    .unwrap();

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    fs::write(out_dir.join("sigstore_root.gen.rs"), out).expect("write sigstore_root.gen.rs");
}
