//! Generates `$OUT_DIR/trust_root.gen.rs` with the pinned trust-root constants
//! the client embeds at build time.
//!
//! Inputs (read from the workspace root):
//!   * `artifact-manifest.json`  — the `enclave` block only; other entries
//!     (per-artifact digests, including this crate's own) are intentionally
//!     ignored so the client build doesn't bust its own cache.
//!   * `releases/trust/trust-constants.json` — non-derivable trust values
//!     (attestant fingerprints, CI identity, schema version pins, update
//!     discovery URLs, server URL template).
//!   * `releases/trust/sigstore-trusted-root.json` — pinned Sigstore tlog /
//!     Fulcio / CT log keys (snapshot of the upstream TrustedRoot).
//!   * `releases/schema/attestation-templates-v1.json` — pinned claim
//!     templates the verifier re-renders during equality checks.
//!
//! Each input file is rerun-watched; the generator validates that everything
//! parses as JSON before emitting. The server URL is derived as
//! `template.replace("{hash}", sha256(snp_bytes || rtmr1_bytes || rtmr2_bytes)
//! [..hash_length_hex_chars])`.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

use sha2::{Digest, Sha256};

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let workspace_root = manifest_dir
        .parent()
        .and_then(Path::parent)
        .expect("workspace root above crates/eidola-app-core")
        .to_path_buf();

    let artifact_manifest_path = workspace_root.join("artifact-manifest.json");
    let trust_constants_path = workspace_root.join("releases/trust/trust-constants.json");
    let sigstore_trusted_root_path =
        workspace_root.join("releases/trust/sigstore-trusted-root.json");
    let attestation_templates_path =
        workspace_root.join("releases/schema/attestation-templates-v1.json");

    for p in [
        &artifact_manifest_path,
        &trust_constants_path,
        &sigstore_trusted_root_path,
        &attestation_templates_path,
    ] {
        println!("cargo:rerun-if-changed={}", p.display());
    }
    println!("cargo:rerun-if-changed=build.rs");

    let artifact_manifest = read_json(&artifact_manifest_path);
    let trust_constants = read_json(&trust_constants_path);

    // Validate sibling JSON files parse, but include the raw bytes verbatim
    // so the on-disk file is the canonical form (no re-serialization drift).
    let _ = read_json(&sigstore_trusted_root_path);
    let _ = read_json(&attestation_templates_path);

    // Gate on artifact-manifest.json schema version so an incompatible
    // future format fails the build with a clear message instead of
    // silently producing wrong constants.
    let manifest_schema_version = get_u32(&artifact_manifest, "schema_version");
    if manifest_schema_version != 1 {
        panic!(
            "artifact-manifest.json schema_version `{manifest_schema_version}` is not supported by this build.rs (expected `1`)"
        );
    }

    let enclave = artifact_manifest
        .get("enclave")
        .expect("artifact-manifest.json missing `enclave` block");
    let snp = get_hex_str(enclave, "snp_measurement", 96);
    let tdx = enclave
        .get("tdx_measurement")
        .expect("artifact-manifest.json missing `enclave.tdx_measurement`");
    let rtmr1 = get_hex_str(tdx, "rtmr1", 96);
    let rtmr2 = get_hex_str(tdx, "rtmr2", 96);

    let url_template = get_str(&trust_constants, "server_url_template");
    let url_hash_length = trust_constants
        .get("server_url_hash_length")
        .and_then(|v| v.as_u64())
        .expect("server_url_hash_length missing or not a number")
        as usize;
    if !url_template.contains("{hash}") {
        panic!("server_url_template must contain `{{hash}}` placeholder");
    }
    let server_url_hash = derive_url_hash(&snp, &rtmr1, &rtmr2, url_hash_length);
    let server_url = url_template.replace("{hash}", &server_url_hash);

    let expected_ci_identity_pattern = get_str(&trust_constants, "expected_ci_identity_pattern");
    let expected_ci_issuer = get_str(&trust_constants, "expected_ci_issuer");
    let update_discovery_url = get_str(&trust_constants, "update_discovery_url");

    let trusted_attestant_fingerprints =
        get_str_array(&trust_constants, "trusted_attestant_fingerprints");
    for fp in &trusted_attestant_fingerprints {
        if fp.len() != 64 || !fp.chars().all(|c| c.is_ascii_hexdigit()) {
            panic!("trusted_attestant_fingerprint must be 64 lowercase hex chars: {fp:?}");
        }
    }
    let supported_release_schema_versions =
        get_u32_array(&trust_constants, "supported_release_schema_versions");
    let supported_attestation_schema_versions =
        get_u32_array(&trust_constants, "supported_attestation_schema_versions");

    let mut out = String::new();
    out.push_str("// @generated by build.rs — do not edit.\n\n");

    push_str_const(&mut out, "SERVER_URL", &server_url);
    push_str_const(&mut out, "SERVER_URL_HASH", &server_url_hash);
    push_str_const(&mut out, "SERVER_SNP_MEASUREMENT", &snp);
    push_str_const(&mut out, "SERVER_TDX_RTMR1", &rtmr1);
    push_str_const(&mut out, "SERVER_TDX_RTMR2", &rtmr2);
    push_str_const(
        &mut out,
        "EXPECTED_CI_IDENTITY_PATTERN",
        expected_ci_identity_pattern,
    );
    push_str_const(&mut out, "EXPECTED_CI_ISSUER", expected_ci_issuer);
    push_str_const(&mut out, "UPDATE_DISCOVERY_URL", update_discovery_url);

    push_str_slice_const(
        &mut out,
        "TRUSTED_ATTESTANT_FINGERPRINTS",
        &trusted_attestant_fingerprints,
    );
    push_u32_slice_const(
        &mut out,
        "SUPPORTED_RELEASE_SCHEMA_VERSIONS",
        &supported_release_schema_versions,
    );
    push_u32_slice_const(
        &mut out,
        "SUPPORTED_ATTESTATION_SCHEMA_VERSIONS",
        &supported_attestation_schema_versions,
    );

    out.push_str(&format!(
        "pub const ATTESTATION_TEMPLATES_JSON: &str = include_str!({:?});\n",
        attestation_templates_path
    ));
    out.push_str(&format!(
        "pub const SIGSTORE_TRUSTED_ROOT_JSON: &str = include_str!({:?});\n",
        sigstore_trusted_root_path
    ));

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    fs::write(out_dir.join("trust_root.gen.rs"), out).expect("write trust_root.gen.rs");
}

fn read_json(path: &Path) -> serde_json::Value {
    let bytes = fs::read(path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
    serde_json::from_slice(&bytes).unwrap_or_else(|e| panic!("parse {}: {e}", path.display()))
}

fn get_str<'a>(value: &'a serde_json::Value, key: &str) -> &'a str {
    value
        .get(key)
        .and_then(|v| v.as_str())
        .unwrap_or_else(|| panic!("missing string field `{key}`"))
}

fn get_str_array(value: &serde_json::Value, key: &str) -> Vec<String> {
    value
        .get(key)
        .and_then(|v| v.as_array())
        .unwrap_or_else(|| panic!("missing array field `{key}`"))
        .iter()
        .map(|v| {
            v.as_str()
                .unwrap_or_else(|| panic!("`{key}` entries must be strings"))
                .to_string()
        })
        .collect()
}

fn get_u32(value: &serde_json::Value, key: &str) -> u32 {
    value
        .get(key)
        .and_then(|v| v.as_u64())
        .and_then(|n| u32::try_from(n).ok())
        .unwrap_or_else(|| panic!("missing or out-of-range u32 field `{key}`"))
}

fn get_u32_array(value: &serde_json::Value, key: &str) -> Vec<u32> {
    value
        .get(key)
        .and_then(|v| v.as_array())
        .unwrap_or_else(|| panic!("missing array field `{key}`"))
        .iter()
        .map(|v| {
            v.as_u64()
                .and_then(|n| u32::try_from(n).ok())
                .unwrap_or_else(|| panic!("`{key}` entries must be u32 integers"))
        })
        .collect()
}

fn get_hex_str(value: &serde_json::Value, key: &str, expected_len: usize) -> String {
    let s = get_str(value, key).to_ascii_lowercase();
    if s.len() != expected_len || !s.chars().all(|c| c.is_ascii_hexdigit()) {
        panic!("`{key}` must be {expected_len} lowercase hex chars, got {s:?}");
    }
    s
}

fn derive_url_hash(snp: &str, rtmr1: &str, rtmr2: &str, hash_len: usize) -> String {
    let mut hasher = Sha256::new();
    hasher.update(decode_hex(snp));
    hasher.update(decode_hex(rtmr1));
    hasher.update(decode_hex(rtmr2));
    let digest = hasher.finalize();
    let mut hex = String::with_capacity(digest.len() * 2);
    for b in digest {
        use std::fmt::Write;
        write!(hex, "{b:02x}").unwrap();
    }
    hex.truncate(hash_len);
    hex
}

fn decode_hex(s: &str) -> Vec<u8> {
    (0..s.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&s[i..i + 2], 16).expect("valid hex"))
        .collect()
}

fn push_str_const(out: &mut String, name: &str, value: &str) {
    out.push_str(&format!("pub const {name}: &str = {value:?};\n"));
}

fn push_str_slice_const(out: &mut String, name: &str, values: &[String]) {
    out.push_str(&format!("pub const {name}: &[&str] = &["));
    for (i, v) in values.iter().enumerate() {
        if i > 0 {
            out.push_str(", ");
        }
        out.push_str(&format!("{v:?}"));
    }
    out.push_str("];\n");
}

fn push_u32_slice_const(out: &mut String, name: &str, values: &[u32]) {
    out.push_str(&format!("pub const {name}: &[u32] = &["));
    for (i, v) in values.iter().enumerate() {
        if i > 0 {
            out.push_str(", ");
        }
        out.push_str(&format!("{v}"));
    }
    out.push_str("];\n");
}
