#!/usr/bin/env python3
"""Generate src/pysem/tables.rs: the CPython data the argument converter needs.

- `html.entities.html5` plus `html`'s invalid character-reference tables, for
  a faithful `html.unescape`;
- the characters `str.isspace()` accepts, which `str.strip()`, `int()` and
  `float()` treat as whitespace;
- the Unicode decimal digits `int()` and `float()` accept, as runs.

Dev-only; the output is committed. Run with the pinned interpreter
(requirements.txt) so the Unicode version matches the reference:

    python -I dev/gen_tables.py
"""

import html
import html.entities
import pathlib
import sys
import unicodedata

CRATE = pathlib.Path(__file__).resolve().parent.parent


def rust_str(s):
    out = []
    for c in s:
        o = ord(c)
        if c == '"':
            out.append('\\"')
        elif c == "\\":
            out.append("\\\\")
        elif 0x20 <= o < 0x7F:
            out.append(c)
        else:
            out.append(f"\\u{{{o:x}}}")
    return '"' + "".join(out) + '"'


def ranges(predicate):
    runs = []
    start = None
    for cp in range(0x110000 + 1):
        ok = cp <= 0x10FFFF and predicate(cp)
        if ok and start is None:
            start = cp
        elif not ok and start is not None:
            runs.append((start, cp - 1))
            start = None
    return runs


def main():
    lines = [
        "// Generated by dev/gen_tables.py; do not edit.",
        f"// Python {sys.version.split()[0]}, Unicode {unicodedata.unidata_version}.",
        "",
        "/// `html.entities.html5`, sorted by name.",
        "pub(crate) static HTML5_ENTITIES: &[(&str, &str)] = &[",
    ]
    for name in sorted(html.entities.html5):
        lines.append(f"    ({rust_str(name)}, {rust_str(html.entities.html5[name])}),")
    lines.append("];")
    lines.append("")
    lines.append("/// `html._invalid_charrefs`.")
    lines.append("pub(crate) static INVALID_CHARREFS: &[(u32, &str)] = &[")
    for num in sorted(html._invalid_charrefs):
        lines.append(f"    (0x{num:x}, {rust_str(html._invalid_charrefs[num])}),")
    lines.append("];")
    lines.append("")
    lines.append("/// `html._invalid_codepoints`, sorted.")
    lines.append("pub(crate) static INVALID_CODEPOINTS: &[u32] = &[")
    for num in sorted(html._invalid_codepoints):
        lines.append(f"    0x{num:x},")
    lines.append("];")
    lines.append("")
    lines.append("/// Inclusive ranges of characters for which `str.isspace()` is true.")
    lines.append("pub(crate) static PY_WHITESPACE: &[(u32, u32)] = &[")
    for lo, hi in ranges(lambda cp: chr(cp).isspace()):
        lines.append(f"    (0x{lo:x}, 0x{hi:x}),")
    lines.append("];")
    lines.append("")
    lines.append("/// Inclusive ranges of Unicode decimal digits, with the value of the first.")
    lines.append("pub(crate) static PY_DECIMAL_DIGITS: &[(u32, u32, u8)] = &[")
    runs = []
    for cp in range(0x110000):
        value = unicodedata.decimal(chr(cp), None)
        if value is None:
            continue
        if runs and runs[-1][1] == cp - 1 and runs[-1][2] + (cp - runs[-1][0]) == value:
            runs[-1][1] = cp
        else:
            runs.append([cp, cp, value])
    for lo, hi, first in runs:
        lines.append(f"    (0x{lo:x}, 0x{hi:x}, {first}),")
    lines.append("];")
    out = CRATE / "src" / "pysem" / "tables.rs"
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
