#!/usr/bin/env bash
set -euo pipefail

if ! git rev-parse --show-toplevel >/dev/null 2>&1; then
    echo "error: not in a git repository" >&2
    exit 1
fi

REPO_ROOT="$(git rev-parse --show-toplevel)"
SOURCE_BINDINGS="${1:-}"
SOURCE_TYPES="${2:-}"

if [[ -z "$SOURCE_BINDINGS" || -z "$SOURCE_TYPES" ]]; then
  echo "No inputs provided. Generating locally..."

  # Build the shared library first to get the dylib
  echo "Building eidola-shared..."
  (cd "$REPO_ROOT" && cargo build -p eidola-shared)

  # Locate the dylib (heuristic for macOS/Linux)
  # TODO: Handle release builds if needed, defaulting to debug for dev
  DYLIB="$REPO_ROOT/target/debug/libeidola_shared.dylib"
  if [[ ! -f "$DYLIB" ]]; then
    DYLIB="$REPO_ROOT/target/debug/libeidola_shared.so"
  fi
  
  if [[ ! -f "$DYLIB" ]]; then
     echo "Error: Could not find built dylib at $REPO_ROOT/target/debug/libeidola_shared.{dylib,so}"
     exit 1
  fi

  # Create temp output directory
  TEMP_OUT="$REPO_ROOT/target/generated-swift"
  mkdir -p "$TEMP_OUT"
  
  echo "Generating UniFFI bindings..."
  (cd "$REPO_ROOT" && cargo run -p uniffi-bindgen-swift -- \
    --swift-sources --headers --modulemap \
    --metadata-no-deps \
    "$DYLIB" \
    "$TEMP_OUT" \
    --module-name eidola_sharedFFI \
    --modulemap-filename module.modulemap)

  # Create the stub C file that Flake creates
  cat > "$TEMP_OUT/eidola_sharedFFI.c" << 'STUB'
// This file exists so Swift Package Manager has something to compile for the eidola_sharedFFI module.
// The actual implementation is in the XCFramework (libeidola_shared.a).
// This module just exposes the C header interface to Swift.
#include "eidola_sharedFFI.h"
STUB

  echo "Generating Crux types..."
  # Clean potential old types
  rm -rf "$TEMP_OUT/SharedTypes"
  (cd "$REPO_ROOT" && cargo run -p shared-typegen -- "$TEMP_OUT")

  # Remove the Package.swift generated by typegen (we use our own)
  rm -f "$TEMP_OUT/SharedTypes/Package.swift"

  SOURCE_BINDINGS="$TEMP_OUT"
  SOURCE_TYPES="$TEMP_OUT"
fi

# Update UniFFI bindings
DEST="$REPO_ROOT/crates/eidola-shared/swift/Sources"
echo "Syncing Swift bindings..."
echo "  Source: $SOURCE_BINDINGS"
echo "  Dest:   $DEST"

mkdir -p "$DEST/EidolaShared"
mkdir -p "$DEST/EidolaSharedFFI"

# Clean old files
rm -f "$DEST/EidolaShared/"*.swift
rm -f "$DEST/EidolaSharedFFI/"*.{h,c,modulemap}

# Copy new files
# Handle both flat outputs (local temp dir) and Nix outputs (Sources/EidolaShared, Sources/EidolaSharedFFI)
if [[ -d "$SOURCE_BINDINGS/EidolaShared" && -d "$SOURCE_BINDINGS/EidolaSharedFFI" ]]; then
  BINDINGS_SWIFT_DIR="$SOURCE_BINDINGS/EidolaShared"
  BINDINGS_FFI_DIR="$SOURCE_BINDINGS/EidolaSharedFFI"
elif [[ -d "$SOURCE_BINDINGS/Sources/EidolaShared" && -d "$SOURCE_BINDINGS/Sources/EidolaSharedFFI" ]]; then
  BINDINGS_SWIFT_DIR="$SOURCE_BINDINGS/Sources/EidolaShared"
  BINDINGS_FFI_DIR="$SOURCE_BINDINGS/Sources/EidolaSharedFFI"
else
  BINDINGS_SWIFT_DIR="$SOURCE_BINDINGS"
  BINDINGS_FFI_DIR="$SOURCE_BINDINGS"
fi

cp "$BINDINGS_SWIFT_DIR/"*.swift "$DEST/EidolaShared/"
cp "$BINDINGS_FFI_DIR/"*.h "$DEST/EidolaSharedFFI/"
cp "$BINDINGS_FFI_DIR/module.modulemap" "$DEST/EidolaSharedFFI/"
cp "$BINDINGS_FFI_DIR/eidola_sharedFFI.c" "$DEST/EidolaSharedFFI/"

# Update Crux typegen types
TYPES_DEST="$REPO_ROOT/crates/eidola-shared/swift/generated"
echo "Syncing Crux typegen Swift types..."
echo "  Source: $SOURCE_TYPES"
echo "  Dest:   $TYPES_DEST"

rm -rf "$TYPES_DEST"
mkdir -p "$TYPES_DEST"
# The source is expected to contain the SharedTypes folder
cp -R "$SOURCE_TYPES/SharedTypes" "$TYPES_DEST/SharedTypes"
chmod -R +w "$TYPES_DEST"

echo "Done. Review changes and commit:"
echo "  git status"
