// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(eidola_app_coreFFI)
  import eidola_app_coreFFI
#endif

extension RustBuffer {
  // Allocate a new buffer, copying the contents of a `UInt8` array.
  fileprivate init(bytes: [UInt8]) {
    let rbuf = bytes.withUnsafeBufferPointer { ptr in
      RustBuffer.from(ptr)
    }
    self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
  }

  fileprivate static func empty() -> RustBuffer {
    RustBuffer(capacity: 0, len: 0, data: nil)
  }

  fileprivate static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
    try! rustCall {
      ffi_eidola_app_core_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0)
    }
  }

  // Frees the buffer in place.
  // The buffer must not be used after this is called.
  fileprivate func deallocate() {
    try! rustCall { ffi_eidola_app_core_rustbuffer_free(self, $0) }
  }
}

extension ForeignBytes {
  fileprivate init(bufferPointer: UnsafeBufferPointer<UInt8>) {
    self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
  }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

extension Data {
  fileprivate init(rustBuffer: RustBuffer) {
    self.init(
      bytesNoCopy: rustBuffer.data!,
      count: Int(rustBuffer.len),
      deallocator: .none
    )
  }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

private func createReader(data: Data) -> (data: Data, offset: Data.Index) {
  (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
private func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws
  -> T
{
  let range = reader.offset..<reader.offset + MemoryLayout<T>.size
  guard reader.data.count >= range.upperBound else {
    throw UniffiInternalError.bufferOverflow
  }
  if T.self == UInt8.self {
    let value = reader.data[reader.offset]
    reader.offset += 1
    return value as! T
  }
  var value: T = 0
  let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range) })
  reader.offset = range.upperBound
  return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
private func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws
  -> [UInt8]
{
  let range = reader.offset..<(reader.offset + count)
  guard reader.data.count >= range.upperBound else {
    throw UniffiInternalError.bufferOverflow
  }
  var value = [UInt8](repeating: 0, count: count)
  value.withUnsafeMutableBufferPointer({ buffer in
    reader.data.copyBytes(to: buffer, from: range)
  })
  reader.offset = range.upperBound
  return value
}

// Reads a float at the current offset.
private func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
  return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
private func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
  return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
private func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
  return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

private func createWriter() -> [UInt8] {
  return []
}

private func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S)
where S: Sequence, S.Element == UInt8 {
  writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
private func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
  var value = value.bigEndian
  withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

private func writeFloat(_ writer: inout [UInt8], _ value: Float) {
  writeInt(&writer, value.bitPattern)
}

private func writeDouble(_ writer: inout [UInt8], _ value: Double) {
  writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
private protocol FfiConverter {
  associatedtype FfiType
  associatedtype SwiftType

  static func lift(_ value: FfiType) throws -> SwiftType
  static func lower(_ value: SwiftType) -> FfiType
  static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
  static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
private protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType {}

extension FfiConverterPrimitive {
  #if swift(>=5.8)
    @_documentation(visibility: private)
  #endif
  public static func lift(_ value: FfiType) throws -> SwiftType {
    return value
  }

  #if swift(>=5.8)
    @_documentation(visibility: private)
  #endif
  public static func lower(_ value: SwiftType) -> FfiType {
    return value
  }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
private protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
  #if swift(>=5.8)
    @_documentation(visibility: private)
  #endif
  public static func lift(_ buf: RustBuffer) throws -> SwiftType {
    var reader = createReader(data: Data(rustBuffer: buf))
    let value = try read(from: &reader)
    if hasRemaining(reader) {
      throw UniffiInternalError.incompleteData
    }
    buf.deallocate()
    return value
  }

  #if swift(>=5.8)
    @_documentation(visibility: private)
  #endif
  public static func lower(_ value: SwiftType) -> RustBuffer {
    var writer = createWriter()
    write(value, into: &writer)
    return RustBuffer(bytes: writer)
  }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
private enum UniffiInternalError: LocalizedError {
  case bufferOverflow
  case incompleteData
  case unexpectedOptionalTag
  case unexpectedEnumCase
  case unexpectedNullPointer
  case unexpectedRustCallStatusCode
  case unexpectedRustCallError
  case unexpectedStaleHandle
  case rustPanic(_ message: String)

  public var errorDescription: String? {
    switch self {
    case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
    case .incompleteData: return "The buffer still has data after lifting its containing value"
    case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
    case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
    case .unexpectedNullPointer: return "Raw pointer value was null"
    case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
    case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
    case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
    case .rustPanic(let message): return message
    }
  }
}

extension NSLock {
  fileprivate func withLock<T>(f: () throws -> T) rethrows -> T {
    self.lock()
    defer { self.unlock() }
    return try f()
  }
}

private let CALL_SUCCESS: Int8 = 0
private let CALL_ERROR: Int8 = 1
private let CALL_UNEXPECTED_ERROR: Int8 = 2
private let CALL_CANCELLED: Int8 = 3

extension RustCallStatus {
  fileprivate init() {
    self.init(
      code: CALL_SUCCESS,
      errorBuf: RustBuffer.init(
        capacity: 0,
        len: 0,
        data: nil
      )
    )
  }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
  let neverThrow: ((RustBuffer) throws -> Never)? = nil
  return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
  _ errorHandler: @escaping (RustBuffer) throws -> E,
  _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T
) throws -> T {
  try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
  _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
  errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
  uniffiEnsureEidolaAppCoreInitialized()
  var callStatus = RustCallStatus.init()
  let returnedVal = callback(&callStatus)
  try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
  return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
  callStatus: RustCallStatus,
  errorHandler: ((RustBuffer) throws -> E)?
) throws {
  switch callStatus.code {
  case CALL_SUCCESS:
    return

  case CALL_ERROR:
    if let errorHandler = errorHandler {
      throw try errorHandler(callStatus.errorBuf)
    } else {
      callStatus.errorBuf.deallocate()
      throw UniffiInternalError.unexpectedRustCallError
    }

  case CALL_UNEXPECTED_ERROR:
    // When the rust code sees a panic, it tries to construct a RustBuffer
    // with the message.  But if that code panics, then it just sends back
    // an empty buffer.
    if callStatus.errorBuf.len > 0 {
      throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
    } else {
      callStatus.errorBuf.deallocate()
      throw UniffiInternalError.rustPanic("Rust panic")
    }

  case CALL_CANCELLED:
    fatalError("Cancellation not supported yet")

  default:
    throw UniffiInternalError.unexpectedRustCallStatusCode
  }
}

private func uniffiTraitInterfaceCall<T>(
  callStatus: UnsafeMutablePointer<RustCallStatus>,
  makeCall: () throws -> T,
  writeReturn: (T) -> Void
) {
  do {
    try writeReturn(makeCall())
  } catch let error {
    callStatus.pointee.code = CALL_UNEXPECTED_ERROR
    callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
  }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
  callStatus: UnsafeMutablePointer<RustCallStatus>,
  makeCall: () throws -> T,
  writeReturn: (T) -> Void,
  lowerError: (E) -> RustBuffer
) {
  do {
    try writeReturn(makeCall())
  } catch let error as E {
    callStatus.pointee.code = CALL_ERROR
    callStatus.pointee.errorBuf = lowerError(error)
  } catch {
    callStatus.pointee.code = CALL_UNEXPECTED_ERROR
    callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
  }
}
// Initial value and increment amount for handles.
// These ensure that SWIFT handles always have the lowest bit set
private let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
private let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

private final class UniffiHandleMap<T>: @unchecked Sendable {
  // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
  private let lock = NSLock()
  private var map: [UInt64: T] = [:]
  private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

  func insert(obj: T) -> UInt64 {
    lock.withLock {
      return doInsert(obj)
    }
  }

  // Low-level insert function, this assumes `lock` is held.
  private func doInsert(_ obj: T) -> UInt64 {
    let handle = currentHandle
    currentHandle += UNIFFI_HANDLEMAP_DELTA
    map[handle] = obj
    return handle
  }

  func get(handle: UInt64) throws -> T {
    try lock.withLock {
      guard let obj = map[handle] else {
        throw UniffiInternalError.unexpectedStaleHandle
      }
      return obj
    }
  }

  func clone(handle: UInt64) throws -> UInt64 {
    try lock.withLock {
      guard let obj = map[handle] else {
        throw UniffiInternalError.unexpectedStaleHandle
      }
      return doInsert(obj)
    }
  }

  @discardableResult
  func remove(handle: UInt64) throws -> T {
    try lock.withLock {
      guard let obj = map.removeValue(forKey: handle) else {
        throw UniffiInternalError.unexpectedStaleHandle
      }
      return obj
    }
  }

  var count: Int {
    map.count
  }
}

// Public interface members begin here.

#if swift(>=5.8)
  @_documentation(visibility: private)
#endif
private struct FfiConverterUInt16: FfiConverterPrimitive {
  typealias FfiType = UInt16
  typealias SwiftType = UInt16

  public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt16 {
    return try lift(readInt(&buf))
  }

  public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
    writeInt(&buf, lower(value))
  }
}

#if swift(>=5.8)
  @_documentation(visibility: private)
#endif
private struct FfiConverterUInt64: FfiConverterPrimitive {
  typealias FfiType = UInt64
  typealias SwiftType = UInt64

  public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
    return try lift(readInt(&buf))
  }

  public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
    writeInt(&buf, lower(value))
  }
}

#if swift(>=5.8)
  @_documentation(visibility: private)
#endif
private struct FfiConverterInt64: FfiConverterPrimitive {
  typealias FfiType = Int64
  typealias SwiftType = Int64

  public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int64 {
    return try lift(readInt(&buf))
  }

  public static func write(_ value: Int64, into buf: inout [UInt8]) {
    writeInt(&buf, lower(value))
  }
}

#if swift(>=5.8)
  @_documentation(visibility: private)
#endif
private struct FfiConverterBool: FfiConverter {
  typealias FfiType = Int8
  typealias SwiftType = Bool

  public static func lift(_ value: Int8) throws -> Bool {
    return value != 0
  }

  public static func lower(_ value: Bool) -> Int8 {
    return value ? 1 : 0
  }

  public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
    return try lift(readInt(&buf))
  }

  public static func write(_ value: Bool, into buf: inout [UInt8]) {
    writeInt(&buf, lower(value))
  }
}

#if swift(>=5.8)
  @_documentation(visibility: private)
#endif
private struct FfiConverterString: FfiConverter {
  typealias SwiftType = String
  typealias FfiType = RustBuffer

  public static func lift(_ value: RustBuffer) throws -> String {
    defer {
      value.deallocate()
    }
    if value.data == nil {
      return String()
    }
    let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
    return String(bytes: bytes, encoding: String.Encoding.utf8)!
  }

  public static func lower(_ value: String) -> RustBuffer {
    return value.utf8CString.withUnsafeBufferPointer { ptr in
      // The swift string gives us int8_t, we want uint8_t.
      ptr.withMemoryRebound(to: UInt8.self) { ptr in
        // The swift string gives us a trailing null byte, we don't want it.
        let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
        return RustBuffer.from(buf)
      }
    }
  }

  public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
    let len: Int32 = try readInt(&buf)
    return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
  }

  public static func write(_ value: String, into buf: inout [UInt8]) {
    let len = Int32(value.utf8.count)
    writeInt(&buf, len)
    writeBytes(&buf, value.utf8)
  }
}

public protocol AppCoreProtocol: AnyObject, Sendable {

  func accountAllocate(credits: Int64) async throws -> AllocateResult

  func accountBalances() async throws -> BalancesResult

  func accountCheckout(priceId: String) async throws -> String

  func accountCreate() async throws -> AccountCreateResult

  func accountPrices() async throws -> [PriceInfo]

  func accountShow() async throws -> AccountShowResult

  func availableModels() async throws -> [ModelInfo]

  func chat(prompt: String, model: String) async throws -> ChatResult

  func configState() -> ConfigState

  func resetAccount() throws

  func setAccountCredentials(id: String, secret: String) throws

  func setAttestationUrl(url: String) throws

  func setBaseUrl(url: String) throws

  func setHardwareIntermediateCa(pem: String) throws

  func setHardwareRootCa(pem: String) throws

  func trustMeasurement(snp: String, tdxRtmr1: String, tdxRtmr2: String) throws -> Bool

  func untrustMeasurement(snp: String) throws -> Bool

  func walletCredentials() async throws -> [CredentialInfo]

}
open class AppCore: AppCoreProtocol, @unchecked Sendable {
  fileprivate let handle: UInt64

  /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
  #if swift(>=5.8)
    @_documentation(visibility: private)
  #endif
  public struct NoHandle {
    public init() {}
  }

  // TODO: We'd like this to be `private` but for Swifty reasons,
  // we can't implement `FfiConverter` without making this `required` and we can't
  // make it `required` without making it `public`.
  #if swift(>=5.8)
    @_documentation(visibility: private)
  #endif
  required public init(unsafeFromHandle handle: UInt64) {
    self.handle = handle
  }

  // This constructor can be used to instantiate a fake object.
  // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
  //
  // - Warning:
  //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
  #if swift(>=5.8)
    @_documentation(visibility: private)
  #endif
  public init(noHandle: NoHandle) {
    self.handle = 0
  }

  #if swift(>=5.8)
    @_documentation(visibility: private)
  #endif
  public func uniffiCloneHandle() -> UInt64 {
    return try! rustCall { uniffi_eidola_app_core_fn_clone_appcore(self.handle, $0) }
  }
  /**
   * Create a new core instance.
   *
   * `config_dir` — directory containing `config.toml`.
   * `data_dir` — directory for the local database.
   */
  public convenience init(configDir: String, dataDir: String) {
    let handle =
      try! rustCall {
        uniffi_eidola_app_core_fn_constructor_appcore_new(
          FfiConverterString.lower(configDir),
          FfiConverterString.lower(dataDir), $0
        )
      }
    self.init(unsafeFromHandle: handle)
  }

  deinit {
    if handle == 0 {
      // Mock objects have handle=0 don't try to free them
      return
    }

    try! rustCall { uniffi_eidola_app_core_fn_free_appcore(handle, $0) }
  }

  open func accountAllocate(credits: Int64) async throws -> AllocateResult {
    return
      try await uniffiRustCallAsync(
        rustFutureFunc: {
          uniffi_eidola_app_core_fn_method_appcore_account_allocate(
            self.uniffiCloneHandle(),
            FfiConverterInt64.lower(credits)
          )
        },
        pollFunc: ffi_eidola_app_core_rust_future_poll_rust_buffer,
        completeFunc: ffi_eidola_app_core_rust_future_complete_rust_buffer,
        freeFunc: ffi_eidola_app_core_rust_future_free_rust_buffer,
        liftFunc: FfiConverterTypeAllocateResult_lift,
        errorHandler: FfiConverterTypeAppError_lift
      )
  }

  open func accountBalances() async throws -> BalancesResult {
    return
      try await uniffiRustCallAsync(
        rustFutureFunc: {
          uniffi_eidola_app_core_fn_method_appcore_account_balances(
            self.uniffiCloneHandle()

          )
        },
        pollFunc: ffi_eidola_app_core_rust_future_poll_rust_buffer,
        completeFunc: ffi_eidola_app_core_rust_future_complete_rust_buffer,
        freeFunc: ffi_eidola_app_core_rust_future_free_rust_buffer,
        liftFunc: FfiConverterTypeBalancesResult_lift,
        errorHandler: FfiConverterTypeAppError_lift
      )
  }

  open func accountCheckout(priceId: String) async throws -> String {
    return
      try await uniffiRustCallAsync(
        rustFutureFunc: {
          uniffi_eidola_app_core_fn_method_appcore_account_checkout(
            self.uniffiCloneHandle(),
            FfiConverterString.lower(priceId)
          )
        },
        pollFunc: ffi_eidola_app_core_rust_future_poll_rust_buffer,
        completeFunc: ffi_eidola_app_core_rust_future_complete_rust_buffer,
        freeFunc: ffi_eidola_app_core_rust_future_free_rust_buffer,
        liftFunc: FfiConverterString.lift,
        errorHandler: FfiConverterTypeAppError_lift
      )
  }

  open func accountCreate() async throws -> AccountCreateResult {
    return
      try await uniffiRustCallAsync(
        rustFutureFunc: {
          uniffi_eidola_app_core_fn_method_appcore_account_create(
            self.uniffiCloneHandle()

          )
        },
        pollFunc: ffi_eidola_app_core_rust_future_poll_rust_buffer,
        completeFunc: ffi_eidola_app_core_rust_future_complete_rust_buffer,
        freeFunc: ffi_eidola_app_core_rust_future_free_rust_buffer,
        liftFunc: FfiConverterTypeAccountCreateResult_lift,
        errorHandler: FfiConverterTypeAppError_lift
      )
  }

  open func accountPrices() async throws -> [PriceInfo] {
    return
      try await uniffiRustCallAsync(
        rustFutureFunc: {
          uniffi_eidola_app_core_fn_method_appcore_account_prices(
            self.uniffiCloneHandle()

          )
        },
        pollFunc: ffi_eidola_app_core_rust_future_poll_rust_buffer,
        completeFunc: ffi_eidola_app_core_rust_future_complete_rust_buffer,
        freeFunc: ffi_eidola_app_core_rust_future_free_rust_buffer,
        liftFunc: FfiConverterSequenceTypePriceInfo.lift,
        errorHandler: FfiConverterTypeAppError_lift
      )
  }

  open func accountShow() async throws -> AccountShowResult {
    return
      try await uniffiRustCallAsync(
        rustFutureFunc: {
          uniffi_eidola_app_core_fn_method_appcore_account_show(
            self.uniffiCloneHandle()

          )
        },
        pollFunc: ffi_eidola_app_core_rust_future_poll_rust_buffer,
        completeFunc: ffi_eidola_app_core_rust_future_complete_rust_buffer,
        freeFunc: ffi_eidola_app_core_rust_future_free_rust_buffer,
        liftFunc: FfiConverterTypeAccountShowResult_lift,
        errorHandler: FfiConverterTypeAppError_lift
      )
  }

  open func availableModels() async throws -> [ModelInfo] {
    return
      try await uniffiRustCallAsync(
        rustFutureFunc: {
          uniffi_eidola_app_core_fn_method_appcore_available_models(
            self.uniffiCloneHandle()

          )
        },
        pollFunc: ffi_eidola_app_core_rust_future_poll_rust_buffer,
        completeFunc: ffi_eidola_app_core_rust_future_complete_rust_buffer,
        freeFunc: ffi_eidola_app_core_rust_future_free_rust_buffer,
        liftFunc: FfiConverterSequenceTypeModelInfo.lift,
        errorHandler: FfiConverterTypeAppError_lift
      )
  }

  open func chat(prompt: String, model: String) async throws -> ChatResult {
    return
      try await uniffiRustCallAsync(
        rustFutureFunc: {
          uniffi_eidola_app_core_fn_method_appcore_chat(
            self.uniffiCloneHandle(),
            FfiConverterString.lower(prompt), FfiConverterString.lower(model)
          )
        },
        pollFunc: ffi_eidola_app_core_rust_future_poll_rust_buffer,
        completeFunc: ffi_eidola_app_core_rust_future_complete_rust_buffer,
        freeFunc: ffi_eidola_app_core_rust_future_free_rust_buffer,
        liftFunc: FfiConverterTypeChatResult_lift,
        errorHandler: FfiConverterTypeAppError_lift
      )
  }

  open func configState() -> ConfigState {
    return try! FfiConverterTypeConfigState_lift(
      try! rustCall {
        uniffi_eidola_app_core_fn_method_appcore_config_state(
          self.uniffiCloneHandle(), $0
        )
      })
  }

  open func resetAccount() throws {
    try rustCallWithError(FfiConverterTypeAppError_lift) {
      uniffi_eidola_app_core_fn_method_appcore_reset_account(
        self.uniffiCloneHandle(), $0
      )
    }
  }

  open func setAccountCredentials(id: String, secret: String) throws {
    try rustCallWithError(FfiConverterTypeAppError_lift) {
      uniffi_eidola_app_core_fn_method_appcore_set_account_credentials(
        self.uniffiCloneHandle(),
        FfiConverterString.lower(id),
        FfiConverterString.lower(secret), $0
      )
    }
  }

  open func setAttestationUrl(url: String) throws {
    try rustCallWithError(FfiConverterTypeAppError_lift) {
      uniffi_eidola_app_core_fn_method_appcore_set_attestation_url(
        self.uniffiCloneHandle(),
        FfiConverterString.lower(url), $0
      )
    }
  }

  open func setBaseUrl(url: String) throws {
    try rustCallWithError(FfiConverterTypeAppError_lift) {
      uniffi_eidola_app_core_fn_method_appcore_set_base_url(
        self.uniffiCloneHandle(),
        FfiConverterString.lower(url), $0
      )
    }
  }

  open func setHardwareIntermediateCa(pem: String) throws {
    try rustCallWithError(FfiConverterTypeAppError_lift) {
      uniffi_eidola_app_core_fn_method_appcore_set_hardware_intermediate_ca(
        self.uniffiCloneHandle(),
        FfiConverterString.lower(pem), $0
      )
    }
  }

  open func setHardwareRootCa(pem: String) throws {
    try rustCallWithError(FfiConverterTypeAppError_lift) {
      uniffi_eidola_app_core_fn_method_appcore_set_hardware_root_ca(
        self.uniffiCloneHandle(),
        FfiConverterString.lower(pem), $0
      )
    }
  }

  open func trustMeasurement(snp: String, tdxRtmr1: String, tdxRtmr2: String) throws -> Bool {
    return try FfiConverterBool.lift(
      try rustCallWithError(FfiConverterTypeAppError_lift) {
        uniffi_eidola_app_core_fn_method_appcore_trust_measurement(
          self.uniffiCloneHandle(),
          FfiConverterString.lower(snp),
          FfiConverterString.lower(tdxRtmr1),
          FfiConverterString.lower(tdxRtmr2), $0
        )
      })
  }

  open func untrustMeasurement(snp: String) throws -> Bool {
    return try FfiConverterBool.lift(
      try rustCallWithError(FfiConverterTypeAppError_lift) {
        uniffi_eidola_app_core_fn_method_appcore_untrust_measurement(
          self.uniffiCloneHandle(),
          FfiConverterString.lower(snp), $0
        )
      })
  }

  open func walletCredentials() async throws -> [CredentialInfo] {
    return
      try await uniffiRustCallAsync(
        rustFutureFunc: {
          uniffi_eidola_app_core_fn_method_appcore_wallet_credentials(
            self.uniffiCloneHandle()

          )
        },
        pollFunc: ffi_eidola_app_core_rust_future_poll_rust_buffer,
        completeFunc: ffi_eidola_app_core_rust_future_complete_rust_buffer,
        freeFunc: ffi_eidola_app_core_rust_future_free_rust_buffer,
        liftFunc: FfiConverterSequenceTypeCredentialInfo.lift,
        errorHandler: FfiConverterTypeAppError_lift
      )
  }

}

#if swift(>=5.8)
  @_documentation(visibility: private)
#endif
public struct FfiConverterTypeAppCore: FfiConverter {
  typealias FfiType = UInt64
  typealias SwiftType = AppCore

  public static func lift(_ handle: UInt64) throws -> AppCore {
    return AppCore(unsafeFromHandle: handle)
  }

  public static func lower(_ value: AppCore) -> UInt64 {
    return value.uniffiCloneHandle()
  }

  public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AppCore {
    let handle: UInt64 = try readInt(&buf)
    return try lift(handle)
  }

  public static func write(_ value: AppCore, into buf: inout [UInt8]) {
    writeInt(&buf, lower(value))
  }
}

#if swift(>=5.8)
  @_documentation(visibility: private)
#endif
public func FfiConverterTypeAppCore_lift(_ handle: UInt64) throws -> AppCore {
  return try FfiConverterTypeAppCore.lift(handle)
}

#if swift(>=5.8)
  @_documentation(visibility: private)
#endif
public func FfiConverterTypeAppCore_lower(_ value: AppCore) -> UInt64 {
  return FfiConverterTypeAppCore.lower(value)
}

public struct AccountCreateResult: Equatable, Hashable {
  public var id: String
  public var createdAt: String

  // Default memberwise initializers are never public by default, so we
  // declare one manually.
  public init(id: String, createdAt: String) {
    self.id = id
    self.createdAt = createdAt
  }

}

#if compiler(>=6)
  extension AccountCreateResult: Sendable {}
#endif

#if swift(>=5.8)
  @_documentation(visibility: private)
#endif
public struct FfiConverterTypeAccountCreateResult: FfiConverterRustBuffer {
  public static func read(from buf: inout (data: Data, offset: Data.Index)) throws
    -> AccountCreateResult
  {
    return
      try AccountCreateResult(
        id: FfiConverterString.read(from: &buf),
        createdAt: FfiConverterString.read(from: &buf)
      )
  }

  public static func write(_ value: AccountCreateResult, into buf: inout [UInt8]) {
    FfiConverterString.write(value.id, into: &buf)
    FfiConverterString.write(value.createdAt, into: &buf)
  }
}

#if swift(>=5.8)
  @_documentation(visibility: private)
#endif
public func FfiConverterTypeAccountCreateResult_lift(_ buf: RustBuffer) throws
  -> AccountCreateResult
{
  return try FfiConverterTypeAccountCreateResult.lift(buf)
}

#if swift(>=5.8)
  @_documentation(visibility: private)
#endif
public func FfiConverterTypeAccountCreateResult_lower(_ value: AccountCreateResult) -> RustBuffer {
  return FfiConverterTypeAccountCreateResult.lower(value)
}

public struct AccountShowResult: Equatable, Hashable {
  public var id: String
  public var stripeCustomerId: String?
  public var createdAt: String

  // Default memberwise initializers are never public by default, so we
  // declare one manually.
  public init(id: String, stripeCustomerId: String?, createdAt: String) {
    self.id = id
    self.stripeCustomerId = stripeCustomerId
    self.createdAt = createdAt
  }

}

#if compiler(>=6)
  extension AccountShowResult: Sendable {}
#endif

#if swift(>=5.8)
  @_documentation(visibility: private)
#endif
public struct FfiConverterTypeAccountShowResult: FfiConverterRustBuffer {
  public static func read(from buf: inout (data: Data, offset: Data.Index)) throws
    -> AccountShowResult
  {
    return
      try AccountShowResult(
        id: FfiConverterString.read(from: &buf),
        stripeCustomerId: FfiConverterOptionString.read(from: &buf),
        createdAt: FfiConverterString.read(from: &buf)
      )
  }

  public static func write(_ value: AccountShowResult, into buf: inout [UInt8]) {
    FfiConverterString.write(value.id, into: &buf)
    FfiConverterOptionString.write(value.stripeCustomerId, into: &buf)
    FfiConverterString.write(value.createdAt, into: &buf)
  }
}

#if swift(>=5.8)
  @_documentation(visibility: private)
#endif
public func FfiConverterTypeAccountShowResult_lift(_ buf: RustBuffer) throws -> AccountShowResult {
  return try FfiConverterTypeAccountShowResult.lift(buf)
}

#if swift(>=5.8)
  @_documentation(visibility: private)
#endif
public func FfiConverterTypeAccountShowResult_lower(_ value: AccountShowResult) -> RustBuffer {
  return FfiConverterTypeAccountShowResult.lower(value)
}

public struct AllocateResult: Equatable, Hashable {
  public var nonce: String
  public var credits: Int64
  public var issuerKeyId: String

  // Default memberwise initializers are never public by default, so we
  // declare one manually.
  public init(nonce: String, credits: Int64, issuerKeyId: String) {
    self.nonce = nonce
    self.credits = credits
    self.issuerKeyId = issuerKeyId
  }

}

#if compiler(>=6)
  extension AllocateResult: Sendable {}
#endif

#if swift(>=5.8)
  @_documentation(visibility: private)
#endif
public struct FfiConverterTypeAllocateResult: FfiConverterRustBuffer {
  public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AllocateResult
  {
    return
      try AllocateResult(
        nonce: FfiConverterString.read(from: &buf),
        credits: FfiConverterInt64.read(from: &buf),
        issuerKeyId: FfiConverterString.read(from: &buf)
      )
  }

  public static func write(_ value: AllocateResult, into buf: inout [UInt8]) {
    FfiConverterString.write(value.nonce, into: &buf)
    FfiConverterInt64.write(value.credits, into: &buf)
    FfiConverterString.write(value.issuerKeyId, into: &buf)
  }
}

#if swift(>=5.8)
  @_documentation(visibility: private)
#endif
public func FfiConverterTypeAllocateResult_lift(_ buf: RustBuffer) throws -> AllocateResult {
  return try FfiConverterTypeAllocateResult.lift(buf)
}

#if swift(>=5.8)
  @_documentation(visibility: private)
#endif
public func FfiConverterTypeAllocateResult_lower(_ value: AllocateResult) -> RustBuffer {
  return FfiConverterTypeAllocateResult.lower(value)
}

public struct BalancePoolInfo: Equatable, Hashable {
  public var amount: Int64
  public var source: String
  public var expiresAt: String?

  // Default memberwise initializers are never public by default, so we
  // declare one manually.
  public init(amount: Int64, source: String, expiresAt: String?) {
    self.amount = amount
    self.source = source
    self.expiresAt = expiresAt
  }

}

#if compiler(>=6)
  extension BalancePoolInfo: Sendable {}
#endif

#if swift(>=5.8)
  @_documentation(visibility: private)
#endif
public struct FfiConverterTypeBalancePoolInfo: FfiConverterRustBuffer {
  public static func read(from buf: inout (data: Data, offset: Data.Index)) throws
    -> BalancePoolInfo
  {
    return
      try BalancePoolInfo(
        amount: FfiConverterInt64.read(from: &buf),
        source: FfiConverterString.read(from: &buf),
        expiresAt: FfiConverterOptionString.read(from: &buf)
      )
  }

  public static func write(_ value: BalancePoolInfo, into buf: inout [UInt8]) {
    FfiConverterInt64.write(value.amount, into: &buf)
    FfiConverterString.write(value.source, into: &buf)
    FfiConverterOptionString.write(value.expiresAt, into: &buf)
  }
}

#if swift(>=5.8)
  @_documentation(visibility: private)
#endif
public func FfiConverterTypeBalancePoolInfo_lift(_ buf: RustBuffer) throws -> BalancePoolInfo {
  return try FfiConverterTypeBalancePoolInfo.lift(buf)
}

#if swift(>=5.8)
  @_documentation(visibility: private)
#endif
public func FfiConverterTypeBalancePoolInfo_lower(_ value: BalancePoolInfo) -> RustBuffer {
  return FfiConverterTypeBalancePoolInfo.lower(value)
}

public struct BalancesResult: Equatable, Hashable {
  public var available: Int64
  public var pools: [BalancePoolInfo]

  // Default memberwise initializers are never public by default, so we
  // declare one manually.
  public init(available: Int64, pools: [BalancePoolInfo]) {
    self.available = available
    self.pools = pools
  }

}

#if compiler(>=6)
  extension BalancesResult: Sendable {}
#endif

#if swift(>=5.8)
  @_documentation(visibility: private)
#endif
public struct FfiConverterTypeBalancesResult: FfiConverterRustBuffer {
  public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> BalancesResult
  {
    return
      try BalancesResult(
        available: FfiConverterInt64.read(from: &buf),
        pools: FfiConverterSequenceTypeBalancePoolInfo.read(from: &buf)
      )
  }

  public static func write(_ value: BalancesResult, into buf: inout [UInt8]) {
    FfiConverterInt64.write(value.available, into: &buf)
    FfiConverterSequenceTypeBalancePoolInfo.write(value.pools, into: &buf)
  }
}

#if swift(>=5.8)
  @_documentation(visibility: private)
#endif
public func FfiConverterTypeBalancesResult_lift(_ buf: RustBuffer) throws -> BalancesResult {
  return try FfiConverterTypeBalancesResult.lift(buf)
}

#if swift(>=5.8)
  @_documentation(visibility: private)
#endif
public func FfiConverterTypeBalancesResult_lower(_ value: BalancesResult) -> RustBuffer {
  return FfiConverterTypeBalancesResult.lower(value)
}

public struct ChatResult: Equatable, Hashable {
  public var content: String
  public var model: String
  public var inputTokens: Int64?
  public var outputTokens: Int64?
  public var creditsCharged: Int64

  // Default memberwise initializers are never public by default, so we
  // declare one manually.
  public init(
    content: String, model: String, inputTokens: Int64?, outputTokens: Int64?, creditsCharged: Int64
  ) {
    self.content = content
    self.model = model
    self.inputTokens = inputTokens
    self.outputTokens = outputTokens
    self.creditsCharged = creditsCharged
  }

}

#if compiler(>=6)
  extension ChatResult: Sendable {}
#endif

#if swift(>=5.8)
  @_documentation(visibility: private)
#endif
public struct FfiConverterTypeChatResult: FfiConverterRustBuffer {
  public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ChatResult {
    return
      try ChatResult(
        content: FfiConverterString.read(from: &buf),
        model: FfiConverterString.read(from: &buf),
        inputTokens: FfiConverterOptionInt64.read(from: &buf),
        outputTokens: FfiConverterOptionInt64.read(from: &buf),
        creditsCharged: FfiConverterInt64.read(from: &buf)
      )
  }

  public static func write(_ value: ChatResult, into buf: inout [UInt8]) {
    FfiConverterString.write(value.content, into: &buf)
    FfiConverterString.write(value.model, into: &buf)
    FfiConverterOptionInt64.write(value.inputTokens, into: &buf)
    FfiConverterOptionInt64.write(value.outputTokens, into: &buf)
    FfiConverterInt64.write(value.creditsCharged, into: &buf)
  }
}

#if swift(>=5.8)
  @_documentation(visibility: private)
#endif
public func FfiConverterTypeChatResult_lift(_ buf: RustBuffer) throws -> ChatResult {
  return try FfiConverterTypeChatResult.lift(buf)
}

#if swift(>=5.8)
  @_documentation(visibility: private)
#endif
public func FfiConverterTypeChatResult_lower(_ value: ChatResult) -> RustBuffer {
  return FfiConverterTypeChatResult.lower(value)
}

/// Snapshot of the current config for display.
public struct ConfigState: Equatable, Hashable {
  public var baseUrl: String?
  public var hasAccount: Bool
  public var hasAccountSecret: Bool
  public var domainSeparator: String
  public var trustedMeasurements: [MeasurementInfo]
  public var hasHardwareRootCa: Bool
  public var hasHardwareIntermediateCa: Bool
  public var attestationUrl: String?

  // Default memberwise initializers are never public by default, so we
  // declare one manually.
  public init(
    baseUrl: String?, hasAccount: Bool, hasAccountSecret: Bool, domainSeparator: String,
    trustedMeasurements: [MeasurementInfo], hasHardwareRootCa: Bool,
    hasHardwareIntermediateCa: Bool, attestationUrl: String?
  ) {
    self.baseUrl = baseUrl
    self.hasAccount = hasAccount
    self.hasAccountSecret = hasAccountSecret
    self.domainSeparator = domainSeparator
    self.trustedMeasurements = trustedMeasurements
    self.hasHardwareRootCa = hasHardwareRootCa
    self.hasHardwareIntermediateCa = hasHardwareIntermediateCa
    self.attestationUrl = attestationUrl
  }

}

#if compiler(>=6)
  extension ConfigState: Sendable {}
#endif

#if swift(>=5.8)
  @_documentation(visibility: private)
#endif
public struct FfiConverterTypeConfigState: FfiConverterRustBuffer {
  public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ConfigState {
    return
      try ConfigState(
        baseUrl: FfiConverterOptionString.read(from: &buf),
        hasAccount: FfiConverterBool.read(from: &buf),
        hasAccountSecret: FfiConverterBool.read(from: &buf),
        domainSeparator: FfiConverterString.read(from: &buf),
        trustedMeasurements: FfiConverterSequenceTypeMeasurementInfo.read(from: &buf),
        hasHardwareRootCa: FfiConverterBool.read(from: &buf),
        hasHardwareIntermediateCa: FfiConverterBool.read(from: &buf),
        attestationUrl: FfiConverterOptionString.read(from: &buf)
      )
  }

  public static func write(_ value: ConfigState, into buf: inout [UInt8]) {
    FfiConverterOptionString.write(value.baseUrl, into: &buf)
    FfiConverterBool.write(value.hasAccount, into: &buf)
    FfiConverterBool.write(value.hasAccountSecret, into: &buf)
    FfiConverterString.write(value.domainSeparator, into: &buf)
    FfiConverterSequenceTypeMeasurementInfo.write(value.trustedMeasurements, into: &buf)
    FfiConverterBool.write(value.hasHardwareRootCa, into: &buf)
    FfiConverterBool.write(value.hasHardwareIntermediateCa, into: &buf)
    FfiConverterOptionString.write(value.attestationUrl, into: &buf)
  }
}

#if swift(>=5.8)
  @_documentation(visibility: private)
#endif
public func FfiConverterTypeConfigState_lift(_ buf: RustBuffer) throws -> ConfigState {
  return try FfiConverterTypeConfigState.lift(buf)
}

#if swift(>=5.8)
  @_documentation(visibility: private)
#endif
public func FfiConverterTypeConfigState_lower(_ value: ConfigState) -> RustBuffer {
  return FfiConverterTypeConfigState.lower(value)
}

public struct CredentialInfo: Equatable, Hashable {
  public var nonce: String
  public var credits: Int64
  public var generation: Int64

  // Default memberwise initializers are never public by default, so we
  // declare one manually.
  public init(nonce: String, credits: Int64, generation: Int64) {
    self.nonce = nonce
    self.credits = credits
    self.generation = generation
  }

}

#if compiler(>=6)
  extension CredentialInfo: Sendable {}
#endif

#if swift(>=5.8)
  @_documentation(visibility: private)
#endif
public struct FfiConverterTypeCredentialInfo: FfiConverterRustBuffer {
  public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CredentialInfo
  {
    return
      try CredentialInfo(
        nonce: FfiConverterString.read(from: &buf),
        credits: FfiConverterInt64.read(from: &buf),
        generation: FfiConverterInt64.read(from: &buf)
      )
  }

  public static func write(_ value: CredentialInfo, into buf: inout [UInt8]) {
    FfiConverterString.write(value.nonce, into: &buf)
    FfiConverterInt64.write(value.credits, into: &buf)
    FfiConverterInt64.write(value.generation, into: &buf)
  }
}

#if swift(>=5.8)
  @_documentation(visibility: private)
#endif
public func FfiConverterTypeCredentialInfo_lift(_ buf: RustBuffer) throws -> CredentialInfo {
  return try FfiConverterTypeCredentialInfo.lift(buf)
}

#if swift(>=5.8)
  @_documentation(visibility: private)
#endif
public func FfiConverterTypeCredentialInfo_lower(_ value: CredentialInfo) -> RustBuffer {
  return FfiConverterTypeCredentialInfo.lower(value)
}

public struct MeasurementInfo: Equatable, Hashable {
  public var snp: String
  public var tdxRtmr1: String
  public var tdxRtmr2: String

  // Default memberwise initializers are never public by default, so we
  // declare one manually.
  public init(snp: String, tdxRtmr1: String, tdxRtmr2: String) {
    self.snp = snp
    self.tdxRtmr1 = tdxRtmr1
    self.tdxRtmr2 = tdxRtmr2
  }

}

#if compiler(>=6)
  extension MeasurementInfo: Sendable {}
#endif

#if swift(>=5.8)
  @_documentation(visibility: private)
#endif
public struct FfiConverterTypeMeasurementInfo: FfiConverterRustBuffer {
  public static func read(from buf: inout (data: Data, offset: Data.Index)) throws
    -> MeasurementInfo
  {
    return
      try MeasurementInfo(
        snp: FfiConverterString.read(from: &buf),
        tdxRtmr1: FfiConverterString.read(from: &buf),
        tdxRtmr2: FfiConverterString.read(from: &buf)
      )
  }

  public static func write(_ value: MeasurementInfo, into buf: inout [UInt8]) {
    FfiConverterString.write(value.snp, into: &buf)
    FfiConverterString.write(value.tdxRtmr1, into: &buf)
    FfiConverterString.write(value.tdxRtmr2, into: &buf)
  }
}

#if swift(>=5.8)
  @_documentation(visibility: private)
#endif
public func FfiConverterTypeMeasurementInfo_lift(_ buf: RustBuffer) throws -> MeasurementInfo {
  return try FfiConverterTypeMeasurementInfo.lift(buf)
}

#if swift(>=5.8)
  @_documentation(visibility: private)
#endif
public func FfiConverterTypeMeasurementInfo_lower(_ value: MeasurementInfo) -> RustBuffer {
  return FfiConverterTypeMeasurementInfo.lower(value)
}

public struct ModelInfo: Equatable, Hashable {
  public var id: String
  public var contextLength: UInt64

  // Default memberwise initializers are never public by default, so we
  // declare one manually.
  public init(id: String, contextLength: UInt64) {
    self.id = id
    self.contextLength = contextLength
  }

}

#if compiler(>=6)
  extension ModelInfo: Sendable {}
#endif

#if swift(>=5.8)
  @_documentation(visibility: private)
#endif
public struct FfiConverterTypeModelInfo: FfiConverterRustBuffer {
  public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ModelInfo {
    return
      try ModelInfo(
        id: FfiConverterString.read(from: &buf),
        contextLength: FfiConverterUInt64.read(from: &buf)
      )
  }

  public static func write(_ value: ModelInfo, into buf: inout [UInt8]) {
    FfiConverterString.write(value.id, into: &buf)
    FfiConverterUInt64.write(value.contextLength, into: &buf)
  }
}

#if swift(>=5.8)
  @_documentation(visibility: private)
#endif
public func FfiConverterTypeModelInfo_lift(_ buf: RustBuffer) throws -> ModelInfo {
  return try FfiConverterTypeModelInfo.lift(buf)
}

#if swift(>=5.8)
  @_documentation(visibility: private)
#endif
public func FfiConverterTypeModelInfo_lower(_ value: ModelInfo) -> RustBuffer {
  return FfiConverterTypeModelInfo.lower(value)
}

public struct PriceInfo: Equatable, Hashable {
  public var id: String
  public var productName: String
  public var productDescription: String?
  public var amountDisplay: String
  public var recurrence: String
  public var credits: Int64

  // Default memberwise initializers are never public by default, so we
  // declare one manually.
  public init(
    id: String, productName: String, productDescription: String?, amountDisplay: String,
    recurrence: String, credits: Int64
  ) {
    self.id = id
    self.productName = productName
    self.productDescription = productDescription
    self.amountDisplay = amountDisplay
    self.recurrence = recurrence
    self.credits = credits
  }

}

#if compiler(>=6)
  extension PriceInfo: Sendable {}
#endif

#if swift(>=5.8)
  @_documentation(visibility: private)
#endif
public struct FfiConverterTypePriceInfo: FfiConverterRustBuffer {
  public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PriceInfo {
    return
      try PriceInfo(
        id: FfiConverterString.read(from: &buf),
        productName: FfiConverterString.read(from: &buf),
        productDescription: FfiConverterOptionString.read(from: &buf),
        amountDisplay: FfiConverterString.read(from: &buf),
        recurrence: FfiConverterString.read(from: &buf),
        credits: FfiConverterInt64.read(from: &buf)
      )
  }

  public static func write(_ value: PriceInfo, into buf: inout [UInt8]) {
    FfiConverterString.write(value.id, into: &buf)
    FfiConverterString.write(value.productName, into: &buf)
    FfiConverterOptionString.write(value.productDescription, into: &buf)
    FfiConverterString.write(value.amountDisplay, into: &buf)
    FfiConverterString.write(value.recurrence, into: &buf)
    FfiConverterInt64.write(value.credits, into: &buf)
  }
}

#if swift(>=5.8)
  @_documentation(visibility: private)
#endif
public func FfiConverterTypePriceInfo_lift(_ buf: RustBuffer) throws -> PriceInfo {
  return try FfiConverterTypePriceInfo.lift(buf)
}

#if swift(>=5.8)
  @_documentation(visibility: private)
#endif
public func FfiConverterTypePriceInfo_lower(_ value: PriceInfo) -> RustBuffer {
  return FfiConverterTypePriceInfo.lower(value)
}

/// Errors returned by app-core operations.
///
/// Each variant maps to a distinct failure mode so callers (CLI, macOS app)
/// can display appropriate feedback without parsing error strings.
public enum AppError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

  /**
   * A required configuration value is missing (base_url, account, etc.).
   */
  case NotConfigured(
    message: String
  )
  /**
   * An HTTP request failed at the transport layer.
   */
  case Network(
    message: String
  )
  /**
   * Enclave attestation verification failed.
   */
  case Attestation(
    message: String
  )
  /**
   * The server returned a non-success HTTP status.
   */
  case Server(
    status: UInt16, message: String
  )
  /**
   * An anonymous credential operation failed.
   */
  case Credential(
    message: String
  )
  /**
   * A local database operation failed.
   */
  case Database(
    message: String
  )
  /**
   * Configuration read/write error.
   */
  case Config(
    message: String
  )
  /**
   * An internal runtime or system error.
   */
  case Internal(
    message: String
  )

  public var errorDescription: String? {
    String(reflecting: self)
  }

}

#if compiler(>=6)
  extension AppError: Sendable {}
#endif

#if swift(>=5.8)
  @_documentation(visibility: private)
#endif
public struct FfiConverterTypeAppError: FfiConverterRustBuffer {
  typealias SwiftType = AppError

  public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AppError {
    let variant: Int32 = try readInt(&buf)
    switch variant {

    case 1:
      return .NotConfigured(
        message: try FfiConverterString.read(from: &buf)
      )
    case 2:
      return .Network(
        message: try FfiConverterString.read(from: &buf)
      )
    case 3:
      return .Attestation(
        message: try FfiConverterString.read(from: &buf)
      )
    case 4:
      return .Server(
        status: try FfiConverterUInt16.read(from: &buf),
        message: try FfiConverterString.read(from: &buf)
      )
    case 5:
      return .Credential(
        message: try FfiConverterString.read(from: &buf)
      )
    case 6:
      return .Database(
        message: try FfiConverterString.read(from: &buf)
      )
    case 7:
      return .Config(
        message: try FfiConverterString.read(from: &buf)
      )
    case 8:
      return .Internal(
        message: try FfiConverterString.read(from: &buf)
      )

    default: throw UniffiInternalError.unexpectedEnumCase
    }
  }

  public static func write(_ value: AppError, into buf: inout [UInt8]) {
    switch value {

    case .NotConfigured(let message):
      writeInt(&buf, Int32(1))
      FfiConverterString.write(message, into: &buf)

    case .Network(let message):
      writeInt(&buf, Int32(2))
      FfiConverterString.write(message, into: &buf)

    case .Attestation(let message):
      writeInt(&buf, Int32(3))
      FfiConverterString.write(message, into: &buf)

    case .Server(let status, let message):
      writeInt(&buf, Int32(4))
      FfiConverterUInt16.write(status, into: &buf)
      FfiConverterString.write(message, into: &buf)

    case .Credential(let message):
      writeInt(&buf, Int32(5))
      FfiConverterString.write(message, into: &buf)

    case .Database(let message):
      writeInt(&buf, Int32(6))
      FfiConverterString.write(message, into: &buf)

    case .Config(let message):
      writeInt(&buf, Int32(7))
      FfiConverterString.write(message, into: &buf)

    case .Internal(let message):
      writeInt(&buf, Int32(8))
      FfiConverterString.write(message, into: &buf)

    }
  }
}

#if swift(>=5.8)
  @_documentation(visibility: private)
#endif
public func FfiConverterTypeAppError_lift(_ buf: RustBuffer) throws -> AppError {
  return try FfiConverterTypeAppError.lift(buf)
}

#if swift(>=5.8)
  @_documentation(visibility: private)
#endif
public func FfiConverterTypeAppError_lower(_ value: AppError) -> RustBuffer {
  return FfiConverterTypeAppError.lower(value)
}

#if swift(>=5.8)
  @_documentation(visibility: private)
#endif
private struct FfiConverterOptionInt64: FfiConverterRustBuffer {
  typealias SwiftType = Int64?

  public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
    guard let value = value else {
      writeInt(&buf, Int8(0))
      return
    }
    writeInt(&buf, Int8(1))
    FfiConverterInt64.write(value, into: &buf)
  }

  public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
    switch try readInt(&buf) as Int8 {
    case 0: return nil
    case 1: return try FfiConverterInt64.read(from: &buf)
    default: throw UniffiInternalError.unexpectedOptionalTag
    }
  }
}

#if swift(>=5.8)
  @_documentation(visibility: private)
#endif
private struct FfiConverterOptionString: FfiConverterRustBuffer {
  typealias SwiftType = String?

  public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
    guard let value = value else {
      writeInt(&buf, Int8(0))
      return
    }
    writeInt(&buf, Int8(1))
    FfiConverterString.write(value, into: &buf)
  }

  public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
    switch try readInt(&buf) as Int8 {
    case 0: return nil
    case 1: return try FfiConverterString.read(from: &buf)
    default: throw UniffiInternalError.unexpectedOptionalTag
    }
  }
}

#if swift(>=5.8)
  @_documentation(visibility: private)
#endif
private struct FfiConverterSequenceTypeBalancePoolInfo: FfiConverterRustBuffer {
  typealias SwiftType = [BalancePoolInfo]

  public static func write(_ value: [BalancePoolInfo], into buf: inout [UInt8]) {
    let len = Int32(value.count)
    writeInt(&buf, len)
    for item in value {
      FfiConverterTypeBalancePoolInfo.write(item, into: &buf)
    }
  }

  public static func read(from buf: inout (data: Data, offset: Data.Index)) throws
    -> [BalancePoolInfo]
  {
    let len: Int32 = try readInt(&buf)
    var seq = [BalancePoolInfo]()
    seq.reserveCapacity(Int(len))
    for _ in 0..<len {
      seq.append(try FfiConverterTypeBalancePoolInfo.read(from: &buf))
    }
    return seq
  }
}

#if swift(>=5.8)
  @_documentation(visibility: private)
#endif
private struct FfiConverterSequenceTypeCredentialInfo: FfiConverterRustBuffer {
  typealias SwiftType = [CredentialInfo]

  public static func write(_ value: [CredentialInfo], into buf: inout [UInt8]) {
    let len = Int32(value.count)
    writeInt(&buf, len)
    for item in value {
      FfiConverterTypeCredentialInfo.write(item, into: &buf)
    }
  }

  public static func read(from buf: inout (data: Data, offset: Data.Index)) throws
    -> [CredentialInfo]
  {
    let len: Int32 = try readInt(&buf)
    var seq = [CredentialInfo]()
    seq.reserveCapacity(Int(len))
    for _ in 0..<len {
      seq.append(try FfiConverterTypeCredentialInfo.read(from: &buf))
    }
    return seq
  }
}

#if swift(>=5.8)
  @_documentation(visibility: private)
#endif
private struct FfiConverterSequenceTypeMeasurementInfo: FfiConverterRustBuffer {
  typealias SwiftType = [MeasurementInfo]

  public static func write(_ value: [MeasurementInfo], into buf: inout [UInt8]) {
    let len = Int32(value.count)
    writeInt(&buf, len)
    for item in value {
      FfiConverterTypeMeasurementInfo.write(item, into: &buf)
    }
  }

  public static func read(from buf: inout (data: Data, offset: Data.Index)) throws
    -> [MeasurementInfo]
  {
    let len: Int32 = try readInt(&buf)
    var seq = [MeasurementInfo]()
    seq.reserveCapacity(Int(len))
    for _ in 0..<len {
      seq.append(try FfiConverterTypeMeasurementInfo.read(from: &buf))
    }
    return seq
  }
}

#if swift(>=5.8)
  @_documentation(visibility: private)
#endif
private struct FfiConverterSequenceTypeModelInfo: FfiConverterRustBuffer {
  typealias SwiftType = [ModelInfo]

  public static func write(_ value: [ModelInfo], into buf: inout [UInt8]) {
    let len = Int32(value.count)
    writeInt(&buf, len)
    for item in value {
      FfiConverterTypeModelInfo.write(item, into: &buf)
    }
  }

  public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [ModelInfo] {
    let len: Int32 = try readInt(&buf)
    var seq = [ModelInfo]()
    seq.reserveCapacity(Int(len))
    for _ in 0..<len {
      seq.append(try FfiConverterTypeModelInfo.read(from: &buf))
    }
    return seq
  }
}

#if swift(>=5.8)
  @_documentation(visibility: private)
#endif
private struct FfiConverterSequenceTypePriceInfo: FfiConverterRustBuffer {
  typealias SwiftType = [PriceInfo]

  public static func write(_ value: [PriceInfo], into buf: inout [UInt8]) {
    let len = Int32(value.count)
    writeInt(&buf, len)
    for item in value {
      FfiConverterTypePriceInfo.write(item, into: &buf)
    }
  }

  public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [PriceInfo] {
    let len: Int32 = try readInt(&buf)
    var seq = [PriceInfo]()
    seq.reserveCapacity(Int(len))
    for _ in 0..<len {
      seq.append(try FfiConverterTypePriceInfo.read(from: &buf))
    }
    return seq
  }
}
private let UNIFFI_RUST_FUTURE_POLL_READY: Int8 = 0
private let UNIFFI_RUST_FUTURE_POLL_WAKE: Int8 = 1

private let uniffiContinuationHandleMap = UniffiHandleMap<UnsafeContinuation<Int8, Never>>()

private func uniffiRustCallAsync<F, T>(
  rustFutureFunc: () -> UInt64,
  pollFunc: (UInt64, @escaping UniffiRustFutureContinuationCallback, UInt64) -> Void,
  completeFunc: (UInt64, UnsafeMutablePointer<RustCallStatus>) -> F,
  freeFunc: (UInt64) -> Void,
  liftFunc: (F) throws -> T,
  errorHandler: ((RustBuffer) throws -> Swift.Error)?
) async throws -> T {
  // Make sure to call the ensure init function since future creation doesn't have a
  // RustCallStatus param, so doesn't use makeRustCall()
  uniffiEnsureEidolaAppCoreInitialized()
  let rustFuture = rustFutureFunc()
  defer {
    freeFunc(rustFuture)
  }
  var pollResult: Int8
  repeat {
    pollResult = await withUnsafeContinuation {
      pollFunc(
        rustFuture,
        { handle, pollResult in
          uniffiFutureContinuationCallback(handle: handle, pollResult: pollResult)
        },
        uniffiContinuationHandleMap.insert(obj: $0)
      )
    }
  } while pollResult != UNIFFI_RUST_FUTURE_POLL_READY

  return try liftFunc(
    makeRustCall(
      { completeFunc(rustFuture, $0) },
      errorHandler: errorHandler
    ))
}

// Callback handlers for an async calls.  These are invoked by Rust when the future is ready.  They
// lift the return value or error and resume the suspended function.
private func uniffiFutureContinuationCallback(handle: UInt64, pollResult: Int8) {
  if let continuation = try? uniffiContinuationHandleMap.remove(handle: handle) {
    continuation.resume(returning: pollResult)
  } else {
    print("uniffiFutureContinuationCallback invalid handle")
  }
}
public func defaultConfigDir() -> String? {
  return try! FfiConverterOptionString.lift(
    try! rustCall {
      uniffi_eidola_app_core_fn_func_default_config_dir(
        $0
      )
    })
}
public func defaultDataDir() -> String? {
  return try! FfiConverterOptionString.lift(
    try! rustCall {
      uniffi_eidola_app_core_fn_func_default_data_dir(
        $0
      )
    })
}

private enum InitializationResult {
  case ok
  case contractVersionMismatch
  case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
  // Get the bindings contract version from our ComponentInterface
  let bindings_contract_version = 30
  // Get the scaffolding contract version by calling the into the dylib
  let scaffolding_contract_version = ffi_eidola_app_core_uniffi_contract_version()
  if bindings_contract_version != scaffolding_contract_version {
    return InitializationResult.contractVersionMismatch
  }
  if uniffi_eidola_app_core_checksum_func_default_config_dir() != 43040 {
    return InitializationResult.apiChecksumMismatch
  }
  if uniffi_eidola_app_core_checksum_func_default_data_dir() != 26158 {
    return InitializationResult.apiChecksumMismatch
  }
  if uniffi_eidola_app_core_checksum_method_appcore_account_allocate() != 34867 {
    return InitializationResult.apiChecksumMismatch
  }
  if uniffi_eidola_app_core_checksum_method_appcore_account_balances() != 44328 {
    return InitializationResult.apiChecksumMismatch
  }
  if uniffi_eidola_app_core_checksum_method_appcore_account_checkout() != 31502 {
    return InitializationResult.apiChecksumMismatch
  }
  if uniffi_eidola_app_core_checksum_method_appcore_account_create() != 21202 {
    return InitializationResult.apiChecksumMismatch
  }
  if uniffi_eidola_app_core_checksum_method_appcore_account_prices() != 52809 {
    return InitializationResult.apiChecksumMismatch
  }
  if uniffi_eidola_app_core_checksum_method_appcore_account_show() != 41463 {
    return InitializationResult.apiChecksumMismatch
  }
  if uniffi_eidola_app_core_checksum_method_appcore_available_models() != 18987 {
    return InitializationResult.apiChecksumMismatch
  }
  if uniffi_eidola_app_core_checksum_method_appcore_chat() != 22416 {
    return InitializationResult.apiChecksumMismatch
  }
  if uniffi_eidola_app_core_checksum_method_appcore_config_state() != 42267 {
    return InitializationResult.apiChecksumMismatch
  }
  if uniffi_eidola_app_core_checksum_method_appcore_reset_account() != 36033 {
    return InitializationResult.apiChecksumMismatch
  }
  if uniffi_eidola_app_core_checksum_method_appcore_set_account_credentials() != 55697 {
    return InitializationResult.apiChecksumMismatch
  }
  if uniffi_eidola_app_core_checksum_method_appcore_set_attestation_url() != 47640 {
    return InitializationResult.apiChecksumMismatch
  }
  if uniffi_eidola_app_core_checksum_method_appcore_set_base_url() != 46134 {
    return InitializationResult.apiChecksumMismatch
  }
  if uniffi_eidola_app_core_checksum_method_appcore_set_hardware_intermediate_ca() != 52826 {
    return InitializationResult.apiChecksumMismatch
  }
  if uniffi_eidola_app_core_checksum_method_appcore_set_hardware_root_ca() != 58016 {
    return InitializationResult.apiChecksumMismatch
  }
  if uniffi_eidola_app_core_checksum_method_appcore_trust_measurement() != 22168 {
    return InitializationResult.apiChecksumMismatch
  }
  if uniffi_eidola_app_core_checksum_method_appcore_untrust_measurement() != 27936 {
    return InitializationResult.apiChecksumMismatch
  }
  if uniffi_eidola_app_core_checksum_method_appcore_wallet_credentials() != 38373 {
    return InitializationResult.apiChecksumMismatch
  }
  if uniffi_eidola_app_core_checksum_constructor_appcore_new() != 52737 {
    return InitializationResult.apiChecksumMismatch
  }

  return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureEidolaAppCoreInitialized() {
  switch initializationResult {
  case .ok:
    break
  case .contractVersionMismatch:
    fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
  case .apiChecksumMismatch:
    fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
  }
}

// swiftlint:enable all
