name: Suggest pinning GitHub Actions

on:
  pull_request:
    paths:
      - ".github/workflows/*.yml"
      - ".github/workflows/*.yaml"

permissions:
  contents: read
  pull-requests: write

jobs:
  suggest-pins:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Suggest action pins
        uses: suzuki-shunsuke/pinact-action@9d485f86d417fa2b51bef4bf7c55fbdefaef64da # v1.0.0
        with:
          skip_push: true
