[package]
name = "eidola-www"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
publish.workspace = true
license = "MIT OR Apache-2.0"

[dependencies]
pulldown-cmark = { version = "0.13", default-features = false, features = ["html"] }
serde = { version = "1", features = ["derive"] }
sha2 = "0.10"
toml = "1.1"
