//! Embeds the gateway's pinned trust inputs into the binary.
//!
//! Inputs, at the workspace root:
//!
//! - `releases/trust/sigstore-trusted-root.json` — a snapshot of Sigstore's
//!   public Fulcio CAs + Rekor keys, the same file the client's updater embeds
//!   via `eidola-app-core/build.rs`. The runtime upstream-measurement resolver
//!   (`src/upstream_trust`) verifies Tinfoil's release attestations against
//!   it; the Tinfoil upstream's measurement is resolved at runtime, not
//!   embedded.
//! - `releases/trust/engine-enclaves.json` — the engine deployments this
//!   gateway build accepts, per model. Checked against the committed
//!   deployment configs under `deploy/engine/` before it is embedded
//!   (`src/engine_trust/manifest.rs`): a pin that disagrees with the config it
//!   names, or that names no committed config, fails the build.

#[path = "src/engine_trust/manifest.rs"]
mod engine_manifest;

use std::env;
use std::fmt::Write;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let workspace_root = manifest_dir
        .parent()
        .and_then(Path::parent)
        .expect("workspace root above crates/eidola-server-gateway")
        .to_path_buf();

    println!("cargo:rerun-if-changed=build.rs");

    let sigstore_trusted_root_path =
        workspace_root.join("releases/trust/sigstore-trusted-root.json");
    println!(
        "cargo:rerun-if-changed={}",
        sigstore_trusted_root_path.display()
    );
    // Parse-check at build time so a malformed snapshot fails the build, not a
    // request at runtime.
    let sigstore_bytes = fs::read(&sigstore_trusted_root_path)
        .unwrap_or_else(|e| panic!("read {}: {e}", sigstore_trusted_root_path.display()));
    serde_json::from_slice::<serde_json::Value>(&sigstore_bytes)
        .unwrap_or_else(|e| panic!("parse {}: {e}", sigstore_trusted_root_path.display()));

    let mut out = String::new();
    out.push_str("// @generated by build.rs — do not edit.\n");
    writeln!(
        out,
        "pub const SIGSTORE_TRUSTED_ROOT_JSON: &str = include_str!({:?});",
        sigstore_trusted_root_path
    )
    .unwrap();

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    fs::write(out_dir.join("sigstore_root.gen.rs"), out).expect("write sigstore_root.gen.rs");

    println!(
        "cargo:rerun-if-changed={}",
        manifest_dir.join("src/engine_trust/manifest.rs").display()
    );
    let engine_enclaves = engine_enclaves(&workspace_root);
    fs::write(out_dir.join("engine_enclaves.gen.rs"), engine_enclaves)
        .expect("write engine_enclaves.gen.rs");
}

/// The config path of every `deploy/engine/<model>/<variant>/` directory.
/// Every directory counts, whatever it holds, so a deployment missing its
/// config is reported rather than overlooked.
fn committed_deployments(workspace_root: &Path) -> Vec<String> {
    let root = workspace_root.join(engine_manifest::DEPLOY_ROOT);
    println!("cargo:rerun-if-changed={}", root.display());
    let dirs = |dir: &Path| -> Vec<String> {
        let Ok(entries) = fs::read_dir(dir) else {
            return Vec::new();
        };
        let mut names: Vec<String> = entries
            .map(|e| e.unwrap_or_else(|e| panic!("list {}: {e}", dir.display())))
            .filter(|e| e.path().is_dir())
            .map(|e| {
                e.file_name()
                    .into_string()
                    .unwrap_or_else(|n| panic!("{n:?} under {} is not UTF-8", dir.display()))
            })
            .collect();
        names.sort();
        names
    };
    let mut committed = Vec::new();
    for model in dirs(&root) {
        for variant in dirs(&root.join(&model)) {
            committed.push(format!(
                "{}/{model}/{variant}/tinfoil-config.yml",
                engine_manifest::DEPLOY_ROOT
            ));
        }
    }
    committed
}

/// Check `releases/trust/engine-enclaves.json` against the deployments it
/// names and render the pinned models as Rust.
fn engine_enclaves(workspace_root: &Path) -> String {
    let path = workspace_root.join("releases/trust/engine-enclaves.json");
    println!("cargo:rerun-if-changed={}", path.display());
    let bytes = fs::read(&path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
    let mut read = |relative: &str| {
        let file = workspace_root.join(relative);
        println!("cargo:rerun-if-changed={}", file.display());
        fs::read(&file).map_err(|e| format!("read {relative}: {e}"))
    };
    let models = engine_manifest::check(&bytes, &mut read)
        .unwrap_or_else(|e| panic!("releases/trust/engine-enclaves.json is not valid: {e}"));
    let committed = committed_deployments(workspace_root);
    engine_manifest::require_every_deployment_pinned(&committed, &models)
        .unwrap_or_else(|e| panic!("releases/trust/engine-enclaves.json is not valid: {e}"));

    let mut out = String::new();
    out.push_str("// @generated by build.rs — do not edit.\n");
    writeln!(
        out,
        "pub const ENGINE_ENCLAVES_JSON: &str = include_str!({:?});",
        path
    )
    .unwrap();
    out.push_str("pub const PINNED_MODELS: &[PinnedModel] = &[\n");
    for model in &models {
        writeln!(
            out,
            "    PinnedModel {{ id: {:?}, weights: PinnedWeights {{ sha256: {:?}, repo: {:?}, \
             revision: {:?} }}, prompt_cache: PromptCachePolicy {{ enabled: {}, \
             idle_ttl_secs: {}, max_age_secs: {} }}, deployments: &{:?} }},",
            model.id,
            model.weights.sha256,
            model.weights.repo,
            model.weights.revision,
            model.prompt_cache.enabled,
            model.prompt_cache.idle_ttl_secs,
            model.prompt_cache.max_age_secs,
            model.deployments,
        )
        .unwrap();
    }
    out.push_str("];\n");
    out
}
